### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [georgefv/Tea-Cozy-Project#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 3.5/4
* _Comment(s):_ Overall your HTML looks great. I don't see any issues with the way elements are being used and the overall structure/layout of the HTML looks solid. With regards to formatting, one thing to keep in mind is how much whitespace/how many newlines we use between elements. Separating sections with line breaks looks fine, however, we can keep things a bit more concise by limiting the spacing between each element. Additionally, we'll want to make sure all of our styles are within a CSS file, as best practice, instead of inline on an HTML element.
 
### Criteria 2: Visual Layout
* _Score Level:_ 4/4
* _Comment(s):_ The visual layout of the site is pretty much spot on with respect to the design specification. Nice work here 👍 
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4/4
* _Comment(s):_ Flexbox is used appropriately throughout `style.css` to group elements within their sections.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 3.5/4
* _Comment(s):_ Pretty much everything from the design specification (styles, font, images, etc) has been included. The only minor recommendation for improvement I have in this regard is to make sure that the navigation links in the header are the same color as the rest of the text on the page.
 
### Overall Score: 15/16 🔥 
Great work with the project overall! Small areas for improvement regarding HTML formatting and styling were mentioned above. With these fixes, the project will be pretty much perfect!

**Comment by georgefv** [comment]
Thank you very much, you are most kind. I'll pay heed to what you said. Thanks.
